name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dockerize
      run: docker build . --file Dockerfile --tag sito/hyperliquid-telegram-bot:latest
    - name: Publish to Docker Hub
      run: docker push sito/hyperliquid-telegram-bot:latest
