name: Docker publish image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dockerize
      run: docker build . --file Dockerfile --tag sito/hyperliquid-telegram-bot:latest
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Publish to Docker Hub
      run: docker push sito/hyperliquid-telegram-bot:latest
