name: Test

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: "0.5.18"

    - name: Run tests
      run: uv run pytest --cov --cov-report=xml --junitxml=test-results.xml

    # Upload artifacts for a follow-up workflow to publish results (works for fork PRs)
    - name: Upload test results artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml
        if-no-files-found: warn
        retention-days: 7

    - name: Upload coverage artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.xml
        if-no-files-found: warn
        retention-days: 7

    - name: Upload GitHub event payload
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: github-event
        path: ${{ github.event_path }}
        if-no-files-found: error
        retention-days: 7
